fullnameOverride: postgres
auth:
  postgresPassword: development
  database: customer-portal
primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 30432
  persistence:
    enabled: true
    size: 512Mi
